### ISSUE TITLE
npm install does not require superuser privileges

### ISSUE THREAD

**Issue by aneesh-neelam** [sreeram-boyapati/My_Linux_Setup#1]
`npm install` does not require superuser privileges for installing dependencies of an npm project as is present [here](https://github.com/sreeram-boyapati/My_Linux_Setup/blob/73465360e9d755cceb4df67a091fb64b6d892e61/pc_install.sh#L55) . It is needed only if you wish to install the npm package globally. 

For example, the following installs the package in a local `node_modules` directory. 

    $ npm install mongodb --save

Whereas the following installs it globally. On a Linux system, it installs in `/usr/local/lib/node_modules` and adds any binaries to the PATH. 

    # npm install -g express-generator

Note the `$` and `#` at the start. `#` refers to superuser/root. `$` refers to unprivileged user.

**Comment by sreeram-boyapati** [comment]
ofcourse globally.
